name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: make cleanup

    - name: cleanup
      if: github.ref == 'refs/heads/main'
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: make cleanup
