name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    
    - name: cleanup
      env:
        PR_NUMBER: ${{ github.event.number }}
      run: make cleanup
